Start working on Seed.rb. Minor logic fixes.
R1cro/rails-geotagging pull request #10
Opened 2017-05-23 17:56 UTC by R1cro

2017-05-24 09:18 UTC, barmidrol requested changes

2017-05-24 09:18 UTC, barmidrol commented on db/seeds.rb
> +    email: 'ateseyko@qulix.com',
зачем указывать свой рабочий имейл в сидах

2017-05-24 09:18 UTC, barmidrol commented on db/seeds.rb
> +    name: 'R1cro',
зачем указывать свой никнейм в сидах

2017-05-24 09:18 UTC, barmidrol commented on db/seeds.rb
> +  name = "Type-#{rand(1..1000)}"
Более осознанные (информативные, разнообразные) названия типов сделай.

2017-05-24 09:18 UTC, barmidrol commented on app/controllers/dynamic_objects_controller.rb
> +    if DynamicObjectType.exists?
Проверка на существование класса? Зачем?

2017-05-24 09:34 UTC, R1cro commented on app/controllers/dynamic_objects_controller.rb
> +    if DynamicObjectType.exists?
Класса? Или записи в БД?

2017-05-24 09:38 UTC, R1cro commented on db/seeds.rb
> +  name = "Type-#{rand(1..1000)}"
Если только вручную забивать в массив и выбирать из него. Либо кастомно добавлять в Faker.

2017-05-24 10:48 UTC, barmidrol commented on app/controllers/dynamic_objects_controller.rb
> +    if DynamicObjectType.exists?
> if DynamicObjectType.exists?

2017-05-24 11:00 UTC, R1cro commented on app/controllers/dynamic_objects_controller.rb
> +    if DynamicObjectType.exists?
Проверка на то, что есть хоть какой-то тип в БД. В противном случае получаем ошибку.

2017-05-24 11:01 UTC, R1cro commented on app/controllers/dynamic_objects_controller.rb
> +    if DynamicObjectType.exists?
Вместо ошибки идет просто переадрессация на рут страницу с соответствующей нотификацией.

2017-05-25 07:15 UTC, barmidrol commented on db/seeds.rb
> +                   University School Stadium Storage)
Насколько случайны все эти типы? Они должны быть случайными.

2017-05-25 07:15 UTC, barmidrol commented on db/seeds.rb
> +  name = "Field-#{rand(1..100)}"
Опять же, почему не сделать случайные имена для полей?

2017-05-25 07:15 UTC, barmidrol commented on db/seeds.rb
> +  dynamic_object_type_id = rand(1..19)
Есть другой, более очевидный способ для выбора рандомного типа.

2017-05-25 07:15 UTC, barmidrol commented on db/seeds.rb
> +  address = ''
Почему пусто?

2017-05-25 07:15 UTC, barmidrol commented on db/seeds.rb
> +  dynamic_object_type_id = rand(1..19)
Есть другой, более очевидный способ для выбора рандомного типа.

2017-05-25 07:15 UTC, barmidrol commented on db/seeds.rb
> +  name = type
В чем смысл этой строчки?

2017-05-25 09:40 UTC, R1cro commented on db/seeds.rb
> +                   University School Stadium Storage)
Почему они должны быть случайными? Я понимаю объекты могут быть случайными. Но типы почему?

2017-05-25 09:40 UTC, R1cro commented on db/seeds.rb
> +  name = type
Забыл убрать из коммита.

2017-05-25 09:41 UTC, R1cro commented on db/seeds.rb
> +  name = "Field-#{rand(1..100)}"
Хорошо, я сделаю через Faker.

2017-05-25 12:18 UTC, closed without merging