User API Authentication.
R1cro/rails-geotagging pull request #16
Opened 2017-05-30 16:49 UTC by R1cro

2017-05-31 11:20 UTC, barmidrol requested changes
Не вижу фичи про token expiration, хотя я сразу просил об этом.

2017-05-31 11:20 UTC, barmidrol commented on app/controllers/api/api_controller.rb
> +    render json: { error: "Access denied. Your token is totally bullshit. Check it, please." }, status: 401
Давай без этих пафосных сообщений.

2017-05-31 11:20 UTC, barmidrol commented on app/controllers/api/api_controller.rb
> +class API::ApiController < ApplicationController
BaseController

2017-05-31 11:20 UTC, barmidrol commented on app/controllers/api/dynamic_objects_controller.rb
> +  before_action :require_authentication!
Зачем это здесь, если уже написано в контроллере, от которого этот наследуется?

2017-05-31 11:20 UTC, barmidrol commented on app/controllers/api/sessions_controller.rb
> +    resource = current_person
Бесполезное присваивание.

2017-05-31 11:20 UTC, barmidrol commented on app/controllers/api/sessions_controller.rb
> +    resource = current_person
И я думаю, что логаут у тебя не работает. Проверь.

2017-05-31 11:20 UTC, barmidrol commented on config/routes.rb
> +    end
Это должно быть в неймспейсе `/api`.

2017-06-01 09:14 UTC, barmidrol commented
Юнит-тесты на новый функционал напиши еще.

2017-06-02 07:13 UTC, barmidrol requested changes
Переписывать всю логику для того, чтобы потом скопипастить тесты -- неправильно. Верни все назад и напиши тесты именно для того, что написал ты.

2017-06-02 17:03 UTC, R1cro commented
**API Authentication**
----
  Token-Based API Authentication. Returns JSON data about user authentication status.

* **URL**

  `/api/login` for user login
  `/api/logout` for user logout

* **Method:**

  `GET` & `POST`

*  **URL Params**

   **Required:**
    Email and password for User login:
   `user%5Bemail%5D=admin@admin&user%5Bpassword%5D=12345678`

* **Data Params**

  `-H "Authorization: Token token=19daef9f25a1d617d40b91ed5661dce1"`

* **Success Response:**
 1) User login:

  * **Code:** 200 <br />
    **Content:**
   
    ```
    [
      "user": 
      {
        "id": 1,
        "email":"admin@admin",
        "name": "R1cro",
        "auth_token":"128947ed92022ca0022e710eb8eec983",
        "token_created_at":"2017-06-02T16:46:42.475Z",
      }
    ]
    ```

 2) When accessing any web application resource with valid token:

 * **Code:** 200 <br />
    **Content:**
   ```

   [ Requested content ]

   ```

* **Error Response:**

  * **Code:** 500 Internal Server Error <br />

  OR

  * **Code:** 401 UNAUTHORIZED <br />
     **Content:** `{ error : "Wrong login or password." }`

  OR 

  * **Code:** 401 UNAUTHORIZED <br />
     **Content:** `{ error : "Access denied. Your token is invalidated or expired." }`

* **Sample Call:**

`curl -X POST --data "user%5Bemail%5D=admin@admin&user%5Bpassword%5D=12345678" http://localhost:3000/api/login.json`

`curl -H "Authorization: Token token=431a5e75aefb0353d67f41f2b7ea76f5" http://localhost:3000/api/users.json`

`curl -H "Authorization: Token token=431a5e75aefb0353d67f41f2b7ea76f5" -g http://localhost:3000/api/dynamic_objects/search\?center\[lat\]\=53.9116664\&center\[lng\]\=27.5651747\&radius\=3`

2017-06-05 09:49 UTC, barmidrol requested changes

2017-06-05 09:49 UTC, barmidrol commented on spec/controllers/api/sessions_controller_spec.rb
> +        expect(JSON.parse(last_response.body)["error"]).to eq "Access denied. Your token is invalidated or expired."
Если я изменю возвращаемое сообщение в контроллере -- тест упадет. Не гуд.

2017-06-05 09:49 UTC, barmidrol commented on app/controllers/api/sessions_controller.rb
> +    user.invalidate_auth_token
Много лишней логики. Подумай, как убрать.

2017-06-05 09:49 UTC, barmidrol commented on app/controllers/api/sessions_controller.rb
> +    def token_and_options(auth_string)
Опять же, лишняя логика. Можно и без этого обойтись.

2017-06-05 09:49 UTC, barmidrol commented on app/controllers/api/base_controller.rb
> +        User.where(auth_token: token).where("token_created_at >= ?", 1.day.ago).first
Лучше использовать `secure_compare`. 
http://www.ploughthroughruby.co.uk/2016/02/21/timing-attack-ruby-vulnerability.html/
Прочитай и расскажешь потом мне, зачем.

2017-06-05 10:07 UTC, R1cro commented on spec/controllers/api/sessions_controller_spec.rb
> +        expect(JSON.parse(last_response.body)["error"]).to eq "Access denied. Your token is invalidated or expired."
Я его тогда вообще уберу. Достаточно получить 401-й код и проверить на обнуленный current_user.

2017-06-05 10:49 UTC, R1cro commented on app/controllers/api/sessions_controller.rb
> +    user.invalidate_auth_token
```
    auth_token, _options = ActionController::HttpAuthentication::Token.token_and_options(request)
    user = User.find_by(auth_token: auth_token)
    user.invalidate_auth_token
```

2017-06-05 10:51 UTC, barmidrol commented on app/controllers/api/sessions_controller.rb
> +    user.invalidate_auth_token
Попробуй добавить метод `current_user` в `API::BaseController`

2017-06-05 10:52 UTC, barmidrol commented on spec/controllers/api/sessions_controller_spec.rb
> +        expect(JSON.parse(last_response.body)["error"]).to eq "Access denied. Your token is invalidated or expired."
Достаточно проверить, что поле `error` что-то в себе содержит.

2017-06-05 10:52 UTC, R1cro commented on app/controllers/api/sessions_controller.rb
> +    user.invalidate_auth_token
Я одной строчкой убрал весь лишний код. Включая нижний метод token_and_options.

2017-06-05 10:52 UTC, R1cro commented on app/controllers/api/sessions_controller.rb
> +    user.invalidate_auth_token
Или все равно current_user?

2017-06-05 10:55 UTC, R1cro commented on app/controllers/api/sessions_controller.rb
> +    user.invalidate_auth_token
А вообще, [вот](http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Token.html#method-i-token_and_options).

2017-06-05 11:09 UTC, barmidrol commented on app/controllers/api/sessions_controller.rb
> +    user.invalidate_auth_token
`current_user` может быть полезен не только в этом конкретном методе. Дабы избежать дублирующей логики по разбору запроса и нахождению юзера, лучше сделать отдельный метод для текущего пользователя и на нем вызвать `invalidate_token`

2018-02-28 22:53 UTC, merged